==== Separation of GORM Async

GORM Async has been separated from GORM core and is no longer added by default to entities.

This was done in order to reduce the number of dependencies necessary to use GORM and to add flexibility in terms of the Async API used in the future.

In order to enable GORM Async you need to add the necessary dependency to `build.gradle`:

[source,groovy,subs="attributes"]
----
compile "org.grails:grails-datastore-gorm-async:{version}"
----

And make your entities implement the `AsyncEntity` trait:

[source,groovy]
----
import grails.gorm.async.*

class Person implements AsyncEntity<Person> {
  ...
}
----

==== Removal of grails-datastore-simple

The `grails-datastore-simple` and `grails-datastore-gorm-test` dependencies have been combined into a single `grails-datastore-gorm-test` dependency.

Unfortunately existing versions of Grails still depend on the old `grails-datastore-simple` dependency. And you may receive an error such as:

[source,groovy,subs="attributes"]
----
> Could not resolve all dependencies for configuration ':example:runtime'.
   > Could not find org.grails:grails-datastore-simple:{version}.
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/grails/grails-datastore-simple/{version}/grails-datastore-simple-{version}.pom
         https://repo.grails.org/grails/core/org/grails/grails-datastore-simple/{version}/grails-datastore-simple-{version}.jar
     Required by:
         project :example > org.grails:grails-dependencies:3.2.4 >
            ...
----

If you are upgrading you will need to exclude this dependency from `grails-dependencies` and remove any references from `build.gradle`. For example:

[source,groovy]
.build.gradle
----
    compile "org.grails:grails-dependencies:$grailsVersion", {
        exclude module:'grails-datastore-simple'
    }
----

==== Flush Mode Now COMMIT by Default

In previous versions of GORM the flush mode defaulted to AUTO. With this setting the session would be flushed with or without the presence of a transaction and before every query.

The frequent flushing of the session before queries can lead to unintended performance consequences if the behaviour of the `AUTO` is not fully understood by the developer.

With this in mind `COMMIT` is the new default flush mode in GORM 6, which will flush the session on transaction commit. You can restore the previous behaviour by configuring the flush mode in your application configuration (for example `application.yml`):

[source,yaml]
----
hibernate:
    flush:
        mode: AUTO
----

==== Multiple Data Source Configuration Changes

Configuration of multiple data sources has changed such that the default data source should be configured at the top level and additional data sources should be configured below the `dataSources` block. In other words instead of:

[source,yaml]
----
dataSources:
    dataSource:
        ...
    anotherDataSource:
        ...
----

The configuration should instead be structured as follows:

[source,yaml]
----
dataSource:
        ...
dataSources:
    anotherDataSource:
        ...
----

In addition Hibernate specific configuration should be nested below each data source definition. For example:


[source,yaml]
----
dataSource:
    url: ".."
hibernate:
    flush:
        mode: COMMIT
dataSources:
    anotherDataSource:
        url: ".."
        hibernate:
            flush:
                mode: AUTO

----

==== Write Operations without a Transaction

With the aforementioned changes to the default flush mode, write operations that are not surrounded by a transaction may not propagate changes to the database unless `flush:true` is explicitly passed or the session explicitly flushed.

Not using a transaction around a write operation is considered bad practise as the connection is essentially in auto commit mode. If your code is structured this way we recommend that you add the necessary `@Transactional` transformation to surround the write operation.

Also note that Hibernate 5.2 and above throw an exception if you attempt a write operation outside of a transaction, and although this is not the case in the current version of GORM it is a possibility that GORM will follow this path and also throw exception for this case in the future.

==== Changes to Configuration Model

In preparation for Hibernate 5.2 support the previous "SessionFactoryBean" notion has been removed. Now if you wish to customize `SessionFactory` creation you should instead register a custom `org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory` in Spring.

==== IdentityEnumType Handling Changed

Previous versions of GORM shipped with a `org.grails.orm.hibernate.cfg.IdentityEnumType` class for altering the handling of enums. In order to support different versions of Hibernate 5.x which feature different signatures for the `org.hibernate.usertype.UserType` interface this class has been removed.

If you wish to obtain the same functionality you need to change your `mapping` block to:

[source,groovy]
----
static mapping = {
   myEnum enumType:"identity"
}
----

==== Changes to Support Hibernate 5.2

Hibernate 5.2 includes many breaking API changes, in order to support Hibernate 5.2 several classes have been removed or rewritten. Including:

* `org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer`
* `org.grails.orm.hibernate.proxy.GroovyAwareJavassistProxyFactory`
* `org.grails.orm.hibernate.persister.entity.GroovyAwareJoinedSubclassEntityPersister`
* `org.grails.orm.hibernate.persister.entity.GroovyAwareSingleTableEntityPersister`

Most of these classes are considered internal, however if you have extended or references these classes you may need to modify your code appropriately.

==== Domain Autowiring Disabled by Default

Spring autowiring of domain instances has been disabled by default because it represents a performance bottleneck. If you are autowiring services into your domain instances you will need to re-enable using the `mapping` block:

[source,groovy]
----
static mapping = {
   autowire true
}
----

Note that if enabled read performance will degrade.

==== Field AccessType by Default

Previous versions of GORM used property access to read and write values to entities by default. In other words the respective getters and setters were used when reflecting on the instances. GORM 6.1 uses field access by default instead, which means the field is used when reading and writing data via reflection to instances.

If you wish to continue to use property access this can be configured by altering the default mapping in your configuration:

[source,groovy]
----
import javax.persistence.*
grails.gorm.default.mapping = {
   '*'(accessType: AccessType.PROPERTY)
}
----

==== Fail on Error Package Setting Renamed

The `grails.gorm.failOnError` setting can no longer be used to configure the packages to enable fail on error. Instead `grails.gorm.failOnErrorPackages` should be used.

==== New Dirty Checking Implementation

GORM now includes its own implementation of dirty checking in order to improve performance. This implementation uses the `DirtyCheckable` trait to store changes in the entity itself so that Hibernate does not have to do internal array comparison to verify whether an object has changed or not.

There may however be some differences in behaviour, so if you wish to continue to use the Hibernate implementatino you can re-enable it with the following configuration:

[source,yaml]
----
hibernate:
    hibernateDirtyChecking: true
----

Some differences in behaviour and workarounds are covered below.

==== Dirty Checking for Abstract Base Classes

Domain objects can inherit from abstract base classes defined in the `src` directory. Previous versions of GORM performed dirty checking automatically on fields from any abstract base class. GORM 6.1 requires that the abstract base class be marked with the `@DirtyCheck` annotation to include the base class fields in domain object dirty checking:

[source,groovy]
----
import grails.gorm.dirty.checking.DirtyCheck

@DirtyCheck
abstract class BaseDomainObject {
    String baseClassField
}
----

==== Dirty Checking for Embedded Classes

Domain objects embed classes defined in the `src` directory. Previous versions of GORM performed dirty checking automatically on fields an embedded entity. GORM 6.1 requires that the embedded class be marked with the `@DirtyCheck` annotation to include the embedded class fields in domain object dirty checking:

[source,groovy]
----
import grails.gorm.dirty.checking.DirtyCheck

@DirtyCheck
abstract class BaseDomainObject {
    String baseClassField
}
----