==== Dependency Upgrades

GORM 7.0 supports a minimum version of Java 8, Hibernate 5.3.x and Spring 5.2.x.

Each of these underlying components may have changes that require altering your application. These changes are beyond the scope of this documentation.


==== Package Restructuring and Deprecations

Previously deprecated classes have been deleted from this release and in order to support Java 11 modules in the future some package re-structuring has occurred.

==== Changes to Proxy Handling

GORM no longer creates custom proxy factories nor automatically unwraps Hibernate proxies.

This makes it more consistent to the way regular Hibernate behaves and reduces the complexity required at the framework level.

You may need to alter `instanceof` checks are manually unwrap proxies in certain cases.

==== Module `grails-validation` Deprecated and Removed

In GORM 6.x the `grails-validation` module was deprecated and replaced by `grails-datastore-gorm-validation`.

Deprecated interfaces were maintained for backwards compatibility. In GORM 7.0 these deprecated classes have been removed and all dependency on `grails-validation` removed.

==== Transactions Now Required for all Operations

Previous versions of Hibernate allowed read operations to be executed without the presence of a declaration transaction.

Hibernate 5.2 and above require the presence of an active transaction. If see a `javax.persistence.TransactionRequiredException` exception it means your method lacks a `@Transactional` annotation around it.