==== Separation of GORM Async

GORM Async has been separated from GORM core and is no longer added by default to entities.

This was done in order to reduce the number of dependencies necessary to use GORM and to add flexibility in terms of the Async API used in the future.

In order to enable GORM Async you need to add the necessary dependency to `build.gradle`:

[source,groovy,subs="attributes"]
----
compile "org.grails:grails-datastore-gorm-async:{version}"
----

And make your entities implement the `AsyncEntity` trait:

[source,groovy]
----
import grails.gorm.async.*

class Person implements AsyncEntity<Person> {
  ...
}
----

==== Removal of grails-datastore-simple

The `grails-datastore-simple` and `grails-datastore-gorm-test` dependencies have been combined into a single `grails-datastore-gorm-test` dependency.

Unfortunately existing versions of Grails still depend on the old `grails-datastore-simple` dependency. And you may receive an error such as:

[source,groovy,subs="attributes"]
----
> Could not resolve all dependencies for configuration ':example:runtime'.
   > Could not find org.grails:grails-datastore-simple:{version}.
     Searched in the following locations:
         https://repo.grails.org/grails/core/org/grails/grails-datastore-simple/{version}/grails-datastore-simple-{version}.pom
         https://repo.grails.org/grails/core/org/grails/grails-datastore-simple/{version}/grails-datastore-simple-{version}.jar
     Required by:
         project :example > org.grails:grails-dependencies:3.2.4 >
            ...
----

If you are upgrading you will need to exclude this dependency from `grails-dependencies` and remove any references from `build.gradle`. For example:

[source,groovy]
.build.gradle
----
    compile "org.grails:grails-dependencies:$grailsVersion", {
        exclude module:'grails-datastore-simple'
    }
----

==== Changes to Configuration Model

In preparation for Hibernate 5.2 support the previous "SessionFactoryBean" notion has been removed. Now if you wish to customize `SessionFactory` creation you should instead register a custom `org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory` in Spring.

==== IdentityEnumType Handling Changed

Previous versions of GORM shipped with a `org.grails.orm.hibernate.cfg.IdentityEnumType` class for altering the handling of enums. In order to support different versions of Hibernate 5.x which feature different signatures for the `org.hibernate.usertype.UserType` interface this class has been removed.

If you wish to obtain the same functionality you need to change your `mapping` block to:

[source,groovy]
----
static mapping = {
   myEnum enumType:"identity"
}
----

==== Changes to Support Hibernate 5.2

Hibernate 5.2 includes many breaking API changes, in order to support Hibernate 5.2 several classes have been removed or rewritten. Including:

* `org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer`
* `org.grails.orm.hibernate.proxy.GroovyAwareJavassistProxyFactory`
* `org.grails.orm.hibernate.persister.entity.GroovyAwareJoinedSubclassEntityPersister`
* `org.grails.orm.hibernate.persister.entity.GroovyAwareSingleTableEntityPersister`

Most of these classes are considered internal, however if you have extended or references these classes you may need to modify your code appropriately.

==== Domain Autowiring Disabled by Default

Spring autowiring of domain instances has been disabled by default because it represents a performance bottleneck. If you are autowiring services into your domain instances you will need to re-enable using the `mapping` block:

[source,groovy]
----
static mapping = {
   autowire true
}
----

Note that if enabled read performance will degrade.

==== Field AccessType by Default

Previous versions of GORM used property access to read and write values to entities by default. In other words the respective getters and setters were used when reflecting on the instances. GORM 6.1 uses field access by default instead, which means the field is used when reading and writing data via reflection to instances.

If you wish to continue to use property access this can be configured by altering the default mapping in your configuration:

[source,groovy]
----
import javax.persistence.*
grails.gorm.default.mapping = {
   '*'(accessType: AccessType.PROPERTY)
}
----

==== Fail on Error Package Setting Renamed

The `grails.gorm.failOnError` setting can no longer be used to configure the packages to enable fail on error. Instead `grails.gorm.failOnErrorPackages` should be used.
