projectVersion=9.0.0-SNAPSHOT
#4.0.2-4.0.3 breaks org.ysb33r.gradle:grolifant for chromedriver
asciidoctorGradleVersion=4.0.1
grolifantVersion=4.0.0
gormVersion=9.0.0-SNAPSHOT
gradleNexusPublishPluginVersion=2.0.0
grailsGradlePluginVersion=7.0.0-SNAPSHOT
grailsShellVersion=7.0.0-SNAPSHOT
grailsSpringSecurityRestVersion=6.0.0-SNAPSHOT
grailsVersion=7.0.0-SNAPSHOT
groovydocGradlePluginVersion=1.0.1
groovyVersion=4.0.24
hibernateVersion=5.6.15.Final
hibernateValidatorVersion=8.0.1.Final
hibernateGroovyProxy=1.1
jansiVersion=2.4.1
javaParserCoreVersion=3.26.2
junitJupiterVersion=5.11.3
picocliVersion=4.7.6
snakeYamlVersion=2.3
slf4jVersion=2.0.16
spockVersion=2.3-groovy-4.0
testingSupportVersion=4.0.0-SNAPSHOT
tomcatLog4jVersion=8.5.2
tomcatVersion=10.1.31
viewsGradleVersion=4.0.0-SNAPSHOT
webdriverBinariesPluginVersion=3.2

org.gradle.caching=true
org.gradle.parallel=false
org.gradle.daemon=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536M -XX:MaxMetaspaceSize=512M