---
grails:
    profile: web
    codegen:
        defaultPackage: datasources
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
    main:
      allow-circular-references: true

---
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  dbCreate: create-drop
  url: jdbc:h2:mem:books;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

