
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:3.3.5")
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: "groovy"

group 'examples'

dependencies {
    implementation platform("org.grails:grails-bom:$grailsVersion")
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation project(":gorm-hibernate5-spring-boot")
    implementation "org.hibernate:hibernate-core-jakarta:$hibernateVersion"
    implementation "org.hibernate:hibernate-ehcache:$hibernateVersion"

    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    runtimeOnly "org.apache.tomcat.embed:tomcat-embed-logging-log4j:$tomcatLog4jVersion"
    runtimeOnly "org.slf4j:slf4j-api"

    testImplementation "org.spockframework:spock-core"

    testRuntimeOnly "org.slf4j:slf4j-simple"

    testImplementation('org.springframework.boot:spring-boot-starter-test')
}
