GORM for Hibernate can be configured with the `grails-app/conf/application.yml` file when using Grails, the `src/main/resources/application.yml` file when using Spring Boot or by passing a `Map` or instanceof the `PropertyResolver` interface to the `org.grails.orm.hibernate.HibernateDatastore` class when used standalone.

All configuration options are read and materialized into an instance of link:../api/org/grails/orm/hibernate/connections/HibernateConnectionSourceSettings.html[HibernateConnectionSourceSettings].

==== Configuration Example

If you are using Grails or Spring Boot, the following is an example of configuration specified in `application.yml`:

[source,yaml]
----
dataSource:
    pooled: true
    dbCreate: create-drop
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password:
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
----

Each one of the settings under the `dataSource` block is set on the link:../api/org/grails/orm/hibernate/jdbc/connections/DataSourceSettings.html[DataSourceSettings] property of `HibernateConnectionSourceSettings`.

Whilst each setting under the `hibernate` block is set on the link:../api/org/grails/orm/hibernate/connections/HibernateConnectionSourceSettings.HibernateSettings.html[HibernateSettings] property.

==== Configuration Reference

You can refer to the link:../api/org/grails/orm/hibernate/connections/HibernateConnectionSourceSettings.html[HibernateConnectionSourceSettings] class for all available configuration options, but below is a table of the common ones:

[format="csv", options="header"]
|===
name,description,default value
`grails.gorm.flushMode`, The flush mode to use, `AUTO`
`grails.gorm.failOnError`, Whether to throw an exception on validation error, `false`
`grails.gorm.default.mapping`,The default mapping to apply to all classes, `null`
`grails.gorm.default.constraints`,The default constraints to apply to all classes, `null`
`grails.gorm.multiTenancy.mode`,The multi tenancy mode, `NONE`
|===

The following are common configuration options for the SQL connection:

[format="csv", options="header"]
|===
name,description,default value
`dataSource.url`, The JDBC url, `jdbc:h2:mem:grailsDB`
`dataSource.driverClassName`, The class of the JDBC driver, detected from URL
`dataSource.username`, The JDBC username, `null`
`dataSource.password`, The JDBC password, `null`
`dataSource.jndiName`, The name of the JNDI resource for the `DataSource`, `null`
`dataSource.pooled`, Whether the connection is pooled, `true`
`dataSource.lazy`, Whether a `LazyConnectionDataSourceProxy` should be used, `true`
`dataSource.transactionAware`, Whether a `TransactionAwareDataSourceProxy` should be used, `true`
`dataSource.readOnly`, Whether the DataSource is read-only, `false`
`dataSource.options`, A map of options to pass to the underlying JDBC driver, `null`
|===

And the following are common configuration options for Hibernate:

[format="csv", options="header"]
|===
name,description,default value
`hibernate.dialect`, The hibernate dialect to use, detected automatically from DataSource
`hibernate.readOnly`, Whether Hibernate should be read-only, `false`
`hibernate.configClass`, The configuration class to use, `HibernateMappingContextConfiguration`
`hibernate.hbm2ddl.auto`, Whether to create the tables on startup, `none`
`hibernate.cache.queries`, Whether to cache queries, `false`
`hibernate.use_second_level_cache`, Whether to use the second level cache, `true`
|===

In addition, any additional settings that start with `hibernate.` are passed through to Hibernate, so if there is any specific feature of Hibernate you wish to configure that is possible.
