Schema-per-tenant is when a single database is used, but a different database schema is used for each tenant.

==== Configuration

In order to activate schema-per-tenant multi-tenancy you need to set the multi-tenancy mode to `SCHEMA` in your configuration and supply a link:../api/org/grails/datastore/mapping/multitenancy/TenantResolver.html[TenantResolver]:

[source,yaml]
----
grails:
    gorm:
        multiTenancy:
            mode: SCHEMA
            tenantResolverClass: foo.bar.MySchemaResolver
dataSource:
    dbCreate: create-drop
    url: jdbc:h2:mem:books
----

The `TenantResolver` must also implement the `AllTenantsResolver` interface and return the schema names of all tenants. This gives you the option to hard code these, place them in configuration or read them from the default schema dynamically.

==== Runtime Schema Creation

On startup, if `dataSource.dbCreate` is set to create the database at runtime, then GORM will attempt to create the schemas if they are missing.

To do this it uses an instance link:../api/org/grails/org/hibernate/jdbc/schema/SchemaHandler.html[SchemaHandler] which by default uses the `CREATE SCHEMA [name]` syntax.

If you want to use this feature and create schemas at runtime depending on the database you may need to configure an alternate implementation:


[source,yaml]
----
dataSource:
    dbCreate: create-drop
    schemaHandler: foo.bar.MySchemaHandler
----

==== Schema-Per-Tenant Caveats

In order to support a schema-per-tenant, just like the `DATABASE` Multi-Tenancy mode, GORM uses a unique `SessionFactory` per tenant. So all of the same considerations regarding session management apply.